from django import forms

class CanaForm(forms.Form):
	Escuela   = forms.CharField(widget=forms.TextInput())
	Turno     = forms.CharField(widget=forms.TextInput())
	Clave     = forms.CharField(widget=forms.TextInput())
	Zona      = forms.CharField(widget=forms.TextInput())
	DirEscl   = forms.CharField(widget=forms.TextInput())
	TelEsc	  = forms.CharField(widget=forms.TextInput())
	Maestro   = forms.CharField(widget=forms.TextInput()) 
	Email     = forms.EmailField(widget=forms.TextInput())
	Apoyo     = forms.CharField(widget=forms.TextInput())
	Porque    = forms.CharField(widget=forms.TextInput())
	Alumno    = forms.CharField(widget=forms.TextInput())
	FechaNci  = forms.CharField(widget=forms.TextInput())
	Edad      = forms.CharField(widget=forms.TextInput())
	Grado     = forms.CharField(widget=forms.TextInput())
	DirAlumno = forms.CharField(widget=forms.TextInput())
	TelAlumno = forms.CharField(widget=forms.TextInput())
	Amigo1    = forms.CharField(widget=forms.TextInput())
	Amigo2    = forms.CharField(widget=forms.TextInput())
	FechaEnfe = forms.CharField(widget=forms.TextInput())
	NomMadre  = forms.CharField(widget=forms.TextInput())
	NomPadre  = forms.CharField(widget=forms.TextInput())